name: Release RPM Bot

on:
  workflow_dispatch:
    inputs:
      type:
        description: 'release type (e.g. rpm/all)'
        default: 'rpm'
        type: string
        required: true
      prerelease:
        description: 'prerelease'
        required: false
        default: '1'
        type: string
      date:
        description: 'date'
        required: false
        default: '0'
        type: string
      snapshot:
        description: 'snapshot'
        required: false
        default: '0'
        type: string


run-name: ref_name:${{ github.ref_name }} type:${{ inputs.type }} prerelease:${{ inputs.prerelease }} date:${{ inputs.date }} snapshot:${{ inputs.snapshot }}

env:
  GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}


jobs:
  get-version:
    uses: ./.github/workflows/get-version.yml
    with:
      prerelease: ${{ inputs.prerelease }}
    secrets: inherit

  release-rpm:
    needs: [ get-version ]
    uses: ./.github/workflows/release-rpm.yml
    with:
      prerelease: ${{ inputs.prerelease }}
      date: ${{ inputs.date }}
      snapshot: ${{ inputs.snapshot }}
    secrets: inherit

  release-rpm-result:
    runs-on: ubuntu-latest
    needs: [ release-rpm ]
    outputs:
      release-result: ${{ steps.get_release_result.outputs.release_result }}
    steps:
      - name: get release result
        id: get_release_result
        run: |
          RELEASE_RESULT="error"
          if [[ "${{ needs.release-rpm.result }}" == "success" ]]; then
              RELEASE_RESULT="success"
          fi
          echo 'release_result='$RELEASE_RESULT >> $GITHUB_OUTPUT

  send-rpm-message:
    needs: [ release-rpm, release-rpm-result ]
    if: ${{ always() }}
    uses: wesql/wesql-cd/.github/workflows/feishui-message.yml@v0.2.0
    with:
      TYPE: "2"
      CONTENT: "release rpm ${{ needs.release-rpm.outputs.release-tag }} ${{ needs.release-rpm-result.outputs.release-result }}"
      APECD_REF: "v0.2.0"
    secrets: inherit

  release-tag:
    runs-on: ubuntu-latest
    needs: [ release-rpm ]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: push tag ${{ needs.release-rpm.outputs.release-tag }}
        uses: mathieudutour/github-tag-action@v6.1
        with:
          custom_tag: ${{ needs.release-rpm.outputs.release-tag }}
          github_token: ${{ env.GITHUB_TOKEN }}
          tag_prefix: ""

  release-image:
    needs: [ get-version, release-rpm ]
    if: ${{ inputs.type == 'all' }}
    uses: ./.github/workflows/release-image.yml@main
    with:
      prerelease: ${{ needs.release-rpm.outputs.prerelease-image }}
      version: ${{ needs.get-version.outputs.mysql-version }}
      wesql_version: ${{ needs.get-version.outputs.wesql-version }}
    secrets: inherit

  release-image-result:
    runs-on: ubuntu-latest
    needs: [ release-image ]
    if: ${{ inputs.type == 'all' }}
    outputs:
      release-result: ${{ steps.get_release_result.outputs.release_result }}
    steps:
      - name: get release result
        id: get_release_result
        run: |
          RELEASE_RESULT="error"
          if [[ "${{ needs.release-image.result }}" == "success" ]]; then
              RELEASE_RESULT="success"
          fi
          echo 'release_result='$RELEASE_RESULT >> $GITHUB_OUTPUT

  send-image-message:
    needs: [ release-rpm, release-image-result ]
    if: ${{ always() && inputs.type == 'all' }}
    uses: wesql/wesql-cd/.github/workflows/feishui-message.yml@v0.2.0
    with:
      TYPE: "2"
      CONTENT: "release image ${{ needs.release-rpm.outputs.release-tag }} ${{ needs.release-image-result.outputs.release-result }}"
      APECD_REF: "v0.2.0"
    secrets: inherit
